baseURL = "https://docs.r-hub.io/"
languageCode = "en-us"
googleAnalytics = "UA-141769052-1"

title = "R-hub Docs"
theme = "kraiklyn"

pygmentsCodeFences = true
pygmentsStyle = "monokailight"

[params]
externalTitle = "R-hub Docs"
description = "Documentation website for the R-hub project of the R Consortium, easing the R package development process."
sidebarColor = "cyan"
customCss = []

[[menu.shortcuts]]
name = "fa fa-archive"
url = "https://builder.r-hub.io/"
weight = 10

[[menu.shortcuts]]
name = "fa fa-github"
url = "https://github.com/r-hub"
weight = 20

[[menu.shortcuts]]
name = "fa fa-twitter"
url = "https://twitter.com/rhub_/"
weight = 20

[[menu.shortcuts]]
name = "fa fa-comments"
url = "https://gitter.im/r-hub/community"
weight = 20

[[menu.shortcuts]]
name = "fa fa-rss"
url = "https://blog.r-hub.io/"
weight = 20

[[menu.shortcuts]]
name = "fa fa-vimeo"
url = "https://vimeo.com/rhub"
weight = 20

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.instagram]
    disable = false
    simple = true
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = false
  [privacy.vimeo]
    disable = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = true