[build]
  publish = "public"
  command =  "hugo"

[context.production.environment]
  HUGO_VERSION = "0.73.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.73.0"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.73.0"

[context.deploy-preview]
command =  "hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command =  "hugo -b $DEPLOY_PRIME_URL"
